=== lost-melody/hanzi-chai-data/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/Character",
	"definitions": {
			"Character": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
							"gb2312": {
									"type": "boolean"
							},
							"readings": {
									"type": "array",
									"items": {
											"type": "string"
									}
							},
							"glyphs": {
									"type": "array",
									"items": {}
							},
							"ambiguous": {
									"type": "boolean"
							},
							"unicode": {
									"type": "number"
							},
							"tygf": {
									"type": "number",
									"enum": [
											0,
											1,
											2,
											3
									]
							},
							"name": {
									"type": [
											"string",
											"null"
									]
							},
							"gf0014_id": {
									"type": [
											"number",
											"null"
									]
							}
					},
					"required": [
							"ambiguous",
							"gb2312",
							"gf0014_id",
							"glyphs",
							"name",
							"readings",
							"tygf",
							"unicode"
					]
			}
	}
}

=== lost-melody/hanzi-chai-data/output.json
[{"unicode":13316,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"basic_component","strokes":[{"feature":"横","start":[20,23],"curveList":[{"command":"h","parameterList":[60]}]},{"feature":"竖折","start":[15,28],"curveList":[{"command":"v","parameterList":[34]},{"command":"h","parameterList":[70]}]},{"feature":"竖","start":[50,4],"curveList":[{"command":"v","parameterList":[90]}]}]}],"name":"降下角","gf0014_id":489,"ambiguous":false},{"unicode":13324,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["","也"]}],"name":"拖右","gf0014_id":null,"ambiguous":false},{"unicode":13355,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["亠","凶"]},{"type":"compound","operator":"⿶","operandList":["凵","文"],"order":[{"index":1,"strokes":0},{"index":0,"strokes":0}]}],"name":"脑右","gf0014_id":null,"ambiguous":true},{"unicode":13356,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["",""]}],"name":"流右","gf0014_id":null,"ambiguous":false},{"unicode":13357,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["亠","回"]}],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":13361,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["人","彡"]}],"name":"珍左","gf0014_id":null,"ambiguous":false},{"unicode":13383,"tygf":1,"gb2312":false,"readings":["zhou4"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":13386,"tygf":1,"gb2312":false,"readings":["yi4"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":13496,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"derived_component","source":"豕","strokes":[{"feature":"点","start":[30,15],"curveList":[{"command":"c","parameterList":[2,3,6,5,8,15]}]},{"feature":"撇","start":[70,15],"curveList":[{"command":"c","parameterList":[-1,3,-2,5,-8,15]}]},{"feature":"reference","index":0},{"feature":"reference","index":1},{"feature":"reference","index":2},{"feature":"reference","index":3},{"feature":"reference","index":4},{"feature":"reference","index":5},{"feature":"reference","index":6}]},{"type":"compound","operator":"⿱","operandList":["丷","豕"]},{"type":"compound","operator":"⿱","operandList":["䒑",""],"tags":["豕省根"]}],"name":"遂内","gf0014_id":null,"ambiguous":true},{"unicode":13505,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["冖","八"]}],"name":"罕上","gf0014_id":null,"ambiguous":false},{"unicode":13534,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿰","operandList":["丰","刀"]}],"name":"契上","gf0014_id":null,"ambiguous":false},{"unicode":13630,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"basic_component","strokes":[{"feature":"横折钩","start":[28,42],"curveList":[{"command":"h","parameterList":[44]},{"command":"v","parameterList":[29]}]},{"feature":"竖弯钩","start":[28,42],"curveList":[{"command":"v","parameterList":[50]},{"command":"h","parameterList":[57]}]}]}],"name":null,"gf0014_id":176,"ambiguous":false},{"unicode":13678,"tygf":1,"gb2312":false,"readings":["fu3"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":13770,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["吅","吅"]}],"name":"四口","gf0014_id":null,"ambiguous":false},{"unicode":13838,"tygf":1,"gb2312":false,"readings":["han3"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":13901,"tygf":1,"gb2312":false,"readings":["duo1"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":13912,"tygf":1,"gb2312":false,"readings":["yao1"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":13926,"tygf":1,"gb2312":false,"readings":["xie2"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":13976,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿰","operandList":["夫","夫"]}],"name":"替上","gf0014_id":null,"ambiguous":false},{"unicode":14019,"tygf":1,"gb2312":false,"readings":["jie2"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14042,"tygf":1,"gb2312":false,"readings":["tong3"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14073,"tygf":1,"gb2312":false,"readings":["pian2"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14153,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["宀","一"]}],"name":"伫右","gf0014_id":null,"ambiguous":false},{"unicode":14196,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿺","operandList":["元","寸"]}],"name":"冠下","gf0014_id":null,"ambiguous":false},{"unicode":14197,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["日",""]}],"name":"得右","gf0014_id":null,"ambiguous":false},{"unicode":14242,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"derived_component","source":"屮","strokes":[{"feature":"reference","index":0},{"feature":"reference","index":1},{"feature":"reference","index":2},{"feature":"横","start":[10,90],"curveList":[{"command":"h","parameterList":[80]}]}]}],"name":"蚩上","gf0014_id":null,"ambiguous":false},{"unicode":14275,"tygf":1,"gb2312":false,"readings":["si1"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14343,"tygf":1,"gb2312":false,"readings":["jiu4"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14355,"tygf":1,"gb2312":false,"readings":["meng2"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14383,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"derived_component","source":"","strokes":[{"feature":"竖","start":[20,20],"curveList":[{"command":"v","parameterList":[60]}]},{"feature":"reference","index":0},{"feature":"reference","index":1},{"feature":"横折","start":[20,60],"curveList":[{"command":"h","parameterList":[60]},{"command":"v","parameterList":[20]}]},{"feature":"横","start":[20,80],"curveList":[{"command":"h","parameterList":[60]}]}]}],"name":"官字底","gf0014_id":506,"ambiguous":false},{"unicode":14400,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"basic_component","strokes":[{"feature":"点","start":[35,18],"curveList":[{"command":"c","parameterList":[3,4,6,10,10,17]}]},{"feature":"撇","start":[65,18],"curveList":[{"command":"c","parameterList":[-2,5,-5,11,-10,17]}]},{"feature":"竖","start":[20,35],"curveList":[{"command":"v","parameterList":[60]}]},{"feature":"横折钩","start":[20,35],"curveList":[{"command":"h","parameterList":[60]},{"command":"v","parameterList":[60]}]},{"feature":"竖","start":[50,5],"curveList":[{"command":"v","parameterList":[90]}]},{"feature":"撇","start":[45,48],"curveList":[{"command":"c","parameterList":[-2,10,-3,19,-10,29]}]},{"feature":"点","start":[55,48],"curveList":[{"command":"c","parameterList":[2,7,5,14,10,29]}]}]}],"name":"敝字旁","gf0014_id":22,"ambiguous":false},{"unicode":14616,"tygf":1,"gb2312":false,"readings":["zhou4"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14660,"tygf":1,"gb2312":false,"readings":["ling2"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14800,"tygf":1,"gb2312":false,"readings":["song3"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14801,"tygf":1,"gb2312":false,"readings":["hui1"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14815,"tygf":1,"gb2312":false,"readings":["kuai3"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":14888,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿰","operandList":["扌","留"]}],"name":"籀下","gf0014_id":null,"ambiguous":false},{"unicode":15063,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["日","子"]}],"name":"厚下","gf0014_id":null,"ambiguous":false},{"unicode":15088,"tygf":1,"gb2312":false,"readings":["lang4"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15114,"tygf":1,"gb2312":false,"readings":["huan3"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15118,"tygf":1,"gb2312":false,"readings":["xian3"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15130,"tygf":1,"gb2312":false,"readings":["che4"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15182,"tygf":1,"gb2312":false,"readings":["gang1"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15189,"tygf":1,"gb2312":false,"readings":["qu1"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15294,"tygf":1,"gb2312":false,"readings":["lang3"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15360,"tygf":1,"gb2312":false,"readings":["li2"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15502,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿰","operandList":["毛","毛"]}],"name":"毳下","gf0014_id":null,"ambiguous":false},{"unicode":15546,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿰","operandList":["氵","七"]}],"name":"柒上","gf0014_id":null,"ambiguous":false},{"unicode":15559,"tygf":1,"gb2312":false,"readings":["fu4"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15576,"tygf":1,"gb2312":false,"readings":["chong1"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15578,"tygf":1,"gb2312":false,"readings":["xu4"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15583,"tygf":0,"gb2312":false,"readings":[],"glyphs":[{"type":"compound","operator":"⿱","operandList":["共","氺"]}],"name":"暴下","gf0014_id":null,"ambiguous":false},{"unicode":15636,"tygf":1,"gb2312":false,"readings":["ji2"],"glyphs":[],"name":null,"gf0014_id":null,"ambiguous":false},{"unicode":15696,"tygf":1,"gb2312":false,
